language: objective-c
osx_image: xcode10
env:
  - SKIP_RPC_TESTS=true

xcode_workspace: CKB.xcworkspace
xcode_scheme: CKB
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
before_install:
  - travis_wait pod repo update --silent
before_script:
  - ./Pods/SwiftLint/swiftlint lint --config .swiftlint.yml --reporter junit
