language: objective-c
osx_image: xcode10.2
env:
  - SKIP_RPC_TESTS=1

xcode_workspace: CKB.xcworkspace
xcode_scheme: CKB
xcode_destination: platform=OS X,arch=x86_64
before_install:
  - gem install cocoapods -N
  - pod --version
  - travis_wait pod repo update --silent
after_success:
  - sleep 5
  - bash <(curl -s https://codecov.io/bash) -J 'CKB'
