language: swift
osx_image: xcode10.2

xcode_workspace: CKB.xcworkspace
xcode_scheme: CKB
xcode_destination: platform=OS X,arch=x86_64

before_install:
  - gem install cocoapods -N
  - pod --version
  - travis_wait pod repo update --silent

matrix:
  include:
    - name: Tests with RPC
      env:
        - SKIP_RPC_TESTS=0
        - CKB_VERSION=v0.14.0-rc2
        - CKB_FILENAME=ckb_${CKB_VERSION}_x86_64-apple-darwin
      before_script:
        - mkdir ckb
        - curl -O -L https://github.com/nervosnetwork/ckb/releases/download/$CKB_VERSION/$CKB_FILENAME.zip
        - unzip $CKB_FILENAME.zip
        - export PATH=$PATH:$PWD/$CKB_FILENAME/
        - ckb init
        - ckb run&


after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'CKB'
